" .vimrc
"
" Maintainer: Narciso Benigno
" Created: Sep 22, 2007
" Notes: Vim 7.0 and beyond

set nocompatible

filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

let mapleader=","

Plugin 'gmarik/Vundle.vim'

Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

Plugin 'tpope/vim-fugitive'

Plugin 'vim-scripts/Gundo'

Plugin 'vim-scripts/bufkill.vim'

Plugin 'scrooloose/syntastic'

Plugin 'tpope/vim-surround'

Plugin 'adelarsq/vim-matchit'
Plugin 'michaeljsmith/vim-indent-object'
Plugin 'kana/vim-textobj-user'
Plugin 'nelstrom/vim-textobj-rubyblock'

Plugin 'vim-ruby/vim-ruby'
Plugin 'tpope/vim-rails'

Plugin 'vim-scripts/groovy.vim'

Plugin 'Raimondi/delimitMate'
Plugin 'tpope/vim-endwise'

Plugin 'ervandew/supertab'
Plugin 'sickill/vim-pasta'

Plugin 'tpope/vim-markdown'
Plugin 'mattn/emmet-vim'
Plugin 'othree/html5.vim'
Plugin 'pangloss/vim-javascript'
Plugin 'kchmck/vim-coffee-script'

Plugin 'puppetlabs/puppet-syntax-vim'

Plugin 'gcatlin/go-vim'
Plugin 'derekwyatt/vim-scala'

Plugin 'altercation/vim-colors-solarized'
Plugin 'jpo/vim-railscasts-theme'

Plugin 'tpope/vim-commentary'

Plugin 'Lokaltog/vim-easymotion'

Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'tomtom/tlib_vim'
Plugin 'honza/vim-snippets'
Plugin 'garbas/vim-snipmate'
Plugin 'scrooloose/nerdtree'
Plugin 'kien/ctrlp.vim'
Plugin 'slim-template/vim-slim'
Plugin 'benmills/vimux'
Plugin 'rking/ag.vim'
Plugin 'jeetsukumaran/vim-buffergator'
Plugin 'AndrewRadev/splitjoin.vim'

" Vim todo
Plugin 'vitalk/vim-simple-todo'

" Haskell
Plugin 'Shougo/vimproc.vim'
Plugin 'raichoo/haskell-vim'
Plugin 'enomsg/vim-haskellConcealPlus'
Plugin 'eagletmt/neco-ghc'
Plugin 'Twinside/vim-hoogle'

Bundle 'vim-scripts/wombat256.vim'

" Python
Plugin 'hdima/python-syntax'

" Cassandra
Plugin 'veegee/cql-vim'

call vundle#end()
filetype plugin indent on
syntax on

let b:manifestspath=$HOME."/.vim/manifests"
for manifest in split(globpath(b:manifestspath, '*.vim'), '\n')
  exec ":source " . manifest
endfor

try
  colorscheme wombat256mod
catch
endtry

" Match wombat colors in nerd tree
hi Directory guifg=#8ac6f2

" Searing red very visible cursor
hi Cursor guibg=red

" Use same color behind concealed unicode characters
hi clear Conceal

" Don't blink normal mode cursor
set guicursor=n-v-c:block-Cursor
set guicursor+=n-v-c:blinkon0

" Set extra options when running in GUI mode
if has("gui_running")
  set guioptions-=T
  set guioptions-=e
  set guitablabel=%M\ %t
endif
set t_Co=256

" Set utf8 as standard encoding and en_US as the standard language
set encoding=utf8

let g:powerline_pycmd='py3'
