---

- name: 'Utilities installation'
  homebrew_cask:
    name: [
        'libffi',
        'gdbm',
        'readline',
        'ruby-install',
        'chruby',
        'wget',
        'python',
        'irssi',
        'jenv',
        'cask',
        'jq',
        'go'
      ]
    state: present
