- hosts: localhost
  connection: local
  vars:
    home: "{{ lookup('env','HOME') }}"
    dev_box_dir: "{{ lookup('env','DEVBOX') }}"
    private_repo: "{{ lookup('env','PRIVATE_GIT_REPO') }}"
  roles:
  - mac/pass
  - mac/git
  - mac/tmux
  - mac/emacs
  - { role: mac/vim, tags: ['vim'] }
  - mac/utilities
  - mac/mac-deps
