- hosts: localhost
  connection: local
  vars:
    home: "{{ lookup('env','HOME') }}"
    dev_box_dir: "{{ lookup('env','DEVBOX') }}"
    private_repo: "{{ lookup('env','PRIVATE_GIT_REPO') }}"
  roles:
  - pass
  - git
  - tmux
  - emacs
  - { role: vim, tags: ['vim'] }
  - utilities
  - mac-deps
  - ctags
