---
- name: 'Tmux installation'
  pacman: name=tmux state=present

- name: 'Link tmux dir'
  file: src="{{ dev_box_dir }}/roles/arch/tmux/files"
        path="{{ home }}/.tmux"
        state=link
        force=yes

- name: 'Link .tmux.conf'
  file: src="{{ home }}/.tmux/tmux.conf"
        path="{{ home }}/.tmux.conf"
        state=link
        force=yes

- git: repo=https://github.com/tmux-plugins/tpm
      dest="{{ home }}/.tmux/plugins/tpm"
