---

- name: 'Vim installation'
  pacman: name=emacs state=present

- name: 'Link .emacs.d dir'
  file: src="{{ dev_box_dir }}/roles/arch/emacs/files/emacs.d"
        path="{{ home }}/.emacs.d"
        state=link
        force=yes

- name: 'Link .vimrc'
  file: src="{{ dev_box_dir }}/roles/arch/emacs/files/spacemacs"
        path="{{ home }}/.spacemacs"
        state=link
        force=yes
