---

- name: 'Vim installation'
  pacman: name=vim
          state=present

- name: 'Installing few required things'
  pacman: name={{ item }} state=present
  with_items:
  - cabal-install
  - the_silver_searcher
  - ghc
  - ctags
  - powerline-fonts

- name: 'Link .vim dir'
  file: src="{{ dev_box_dir }}/roles/arch/vim/files"
        path="{{ home }}/.vim"
        state=link
        force=yes

- name: 'Link .vimrc'
  file: src="{{ home }}/.vim/vimrc"
        path="{{ home }}/.vimrc"
        state=link
        force=yes

- name: 'Install vundle'
  git: repo=https://github.com/VundleVim/Vundle.vim.git
       dest=~/.vim/bundle/Vundle.vim
       force=yes

- name: 'install vim plugins'
  command: vim +PluginInstall +qall

- name: make vim proc
  command: "make --directory={{ home }}/.vim/bundle/vimproc.vim/"
