- name: 'Create kitty conf dir'
  file: path="{{ home }}/.config"
        state=directory
        recurse=true

- name: 'Link kitty.conf'
  file: src="{{ dev_box_dir }}/roles/kitty/files"
        path="{{ home }}/.config/kitty"
        state=link
        force=yes

- name: 'Manual instalation instruction'
  debug: msg='please, install kitty package manually> brew install kitty'
