---

- name: 'Tapping'
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - railwaycat/emacsmacport
    - caskroom/versions

- name: 'Utilities installation'
  homebrew: name={{ item }} state=present
  with_items:
    - libffi
    - gdbm
    - readline
    - ruby-install
    - chruby
    - wget
    - python
    - tmate
    - irssi
    - jenv
    - maven
    - cask
    - jq
