---

- name: 'Tapping'
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - railwaycat/emacsmacport
    - caskroom/versions

- name: 'Installing java 7'
  homebrew_cask: name={{ item }} state=present
  with_items:
    - java7
    - miniconda

- name: 'Utilities installation'
  homebrew: name={{ item }} state=present
  with_items:
    - libffi
    - gdbm
    - readline
    - ruby-install
    - chruby
    - jenv
    - wget
    - python
    - tmate
    - irssi
    - maven
    - cask
    - jq

- name: 'Uninstall deprecateds'
  homebrew: name=boot2docker state=absent
  with_items:
    - boot2docker
    - heroku-toolbelt
