---

- name: 'Tapping'
  homebrew_tap: tap=nviennot/tmate state=present

- name: 'Utilities installation'
  homebrew: name={{ item }} state=present
  with_items:
    - boot2docker
    - libffi
    - gdbm
    - readline
    - ruby-install
    - chruby
    - jenv
    - wget
    - python
    - tmate
