---

- name: 'Mac App installations'
  homebrew_cask: name={{ item }} state=present
  with_items:
    - google-chrome
    - alfred
    - caffeine
    - screenhero
    - slack
    - evernote
    - skype
    - appcleaner
    - firefox
    - telegram
    - spotify
    - sequel-pro
    - emacs

- name: 'Mac App deprecateds'
  homebrew_cask: name={{ item }} state=absent
  with_items:
    - dockertoolbox
    - vagrant
    - virtualbox
